[package]
name = "tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
xerces = { path = "../xerces" }
javax_xml = { path = "../javax_xml" }


[[test]]
name = "jaxp_12_tests"
path = "tests/xerces/jaxp/jaxp_12_tests.rs"
